branches:
  only:
  - master
  - develop
matrix:
  include:
  - os: linux
    sudo: false
    language: android
    android:
      components:
      - tools
      - platform-tools
      - tools
      - build-tools-26.0.0
      - android-25
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
    addons:
      apt:
        packages:
        - oracle-java8-installer
        - oracle-java8-set-default
        - jq
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
  - os: osx
    language: objective-c
    osx_image: xcode8.3

before_install:
- export LANG=en_US.UTF-8
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; brew install yarn ios-sim
  jq ios-deploy cocoapods ; rvm use system ; pod setup ; fi
- nvm install 8
- npm i -g ionic cordova
script:
- npm install
- ionic build

env:
  global:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle
